language: node_js
node_js:
- node
notifications:
  email: false
scripts:
  npm run updateSnapshot
deploy:
  provider: heroku
  api_key:
    secure: bp7YfwnOTlJ+Bp//igoKZViMrLzvuJoiKK4cNnBYVWOUtkGp5TgraDVlXSAgYtpFgCKLeT65KcXvL6Ue9MdrhovpdJ9/31YyiRCeBc0K/BTaHQEYxrQm5n7/XX12RbtGmub0QK/fYoIZO46h5+JKfWB07z5Dnef8nEKdkUwxSajXrRAEsRi8u5ObrvGC/0f/YbmHuI1bhJy0UJnPhhur9IfIZNCf2WiJxMJgrYv7z8gyXUpTqsZMhGbUOH8QjCDSNLZi0Z09CEFqFzhLveX1GTJxnB6wM8FFdbCnvm+PgZYjzpU4qN37a/Jbd2mb8lJ5NCd9RTPP3ipqCK/X7HE2DrTx2NMG87IBv7WxHPA92XwGVxzzqshMlyaor6V56TFBo/0vYfnuyM2d8hXMmMHcL1w9cGE9/345Z2p75KyWIDI5RJb57wU3eYLO4lATX3+1JpZo6CeH5WxOCQvVLp0nA2dXK0oAINsGqdVfObCwOtXnPOO75EtFbssWpy+DG6TG2YJ+GrpsKBGOhS/QC6aoSbzE15iq6CiL5C3MdS0k7060kRXi/DDZgXYDe/lzIZc3EnZ8Me+5Mj3ZIZjIq+np7ML7ptzLUE0+9jkHK4J3Yfxf5xKQU+tTjBlVYhFsjPadoVGoPP5mhBq1BEjlrQPiFNC/DR65mgt51Kc2ayvEWxg=
  app: coderdojo-colorado