language: node_js
node_js:
- node
notifications:
  email: false
before_install:
- export TZ=America/Denver
deploy:
  provider: heroku
  api_key:
    secure: ClVrzx66zy9aaut6MM5KZPn7JsHSH/aTKRTts56nlUHtzjq8a6f74hLY0pVJnMNQWdBS2AGv0RkbKQ8oOqlJPpZVZTYJMe/yjCiaHfQWMr+Q4UFbpa2s3pqNNeeRekJ27JU6vxNN1IqlLnJ2RcIf46VyDDmiOIMP2L+P8ziXEkZbFL79m6K75w4o/JO8AUXhkIgfiToNmRxlZ2ka7cp5oHTRO08rdDxZZsVBGKyHnZJEDrmwVbMKg3p1wcNVW+ul8kX2dQBQ03kPshPU+g399jiyB3Xwf1I1NRe9qpPtwL3weclLc1rH9r8JWv03wl6VV2Ih4jvyMHih1sCy5mFWPRbi5Io9dGdhnpzfjZkK8Zcnh3VEDHVc/nmqfPLOkDw7Hv2HSQ7slqAzn8QvfQ1GgA5/Z5oRDQWx3t9PzNMFe6c40Y7w0UAvc05R5ybUhO9JOaQ4W42kw2jxegtSU5/xHw11/avWXqBWe+XioC5/FhrPvf5Wg8lKAd3W5JN+sQdJ1EDOaB2yJOry72LdQN2Kpu4+DgkyWPOAi2NJpr7AD4Tt3IcprgJzthZMpKb4XSNNRnd71oqFfQ3RQRPCOJpwb/Me9+kB2NCCRVnyKpwHcAby+LIH+R6/8xuUPOG5ov/TZMwJ1UIy82GeiRNZYqbsJXTCYsv1Ys/2296KY5JBGK4=
  app: warm-stream-58372
